# Site settings
title: Luiz's Place
email: luiz@kaze.io
description: > # this means to ignore newlines until "baseurl:"
  Website under construction =)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kaze.io" # the base hostname & protocol for your site
twitter_username: kazenotenshi
github_username:  kazenotenshi

# Build settings
markdown: kramdown
